import { Badge } from "../types";

export const badges: Record<string, Badge[]> = {
  "9745": [
    {
      name: 'Rookie',
      nftId: '1',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/rookie.svg',
      description: 'Everyone starts somewhere. Welcome to the charts.',
      criteria: 'Complete your first trade',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '3',
      totalWalletCap: 10000,
      active: false,
    },
    {
      name: 'Volume Chaser',
      nftId: '2',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/volumeChaser.svg',
      description: 'You’ve got the itch. Every trade fuels the rush.',
      criteria: 'Reach $1,000 cumulative trading volume',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '10',
      totalWalletCap: 10000,
      active: false,
    },
    {
      name: 'Chart Surfer',
      nftId: '3',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/chartSurfer.svg',
      description: 'You ride the waves while others drown in them.',
      criteria: 'Reach $10,000 cumulative trading volume',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '70',
      totalWalletCap: 7500,
      active: false,
    },
    {
      name: 'Position Hunter',
      nftId: '4',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/positionHunter.svg',
      description: 'No luck, just precision. You see setups before they form.',
      criteria: 'Reach $100,000 cumulative trading volume',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '800',
      totalWalletCap: 5000,
      active: false,
    },
    {
      name: 'Perpetual Veteran',
      nftId: '5',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/perpetualVeteran.svg',
      description: 'Battle-tested. Seasoned. You trade with instinct.',
      criteria: 'Reach $1,000,000 cumulative trading volume',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '9000',
      totalWalletCap: 1500,
      active: false,
    },
    {
      name: 'Perpetual Legend',
      nftId: '6',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/perpetualVeteran.svg',
      description: 'You don’t chase the market, the market chases you.',
      criteria: 'Reach $10,000,000 cumulative trading volume',
      type: 'Activity',
      category: 'Trading Progression',
      minPoints: 1000,
      pointsValue: '100000',
      totalWalletCap: 50,
      active: false,
    },
    {
      name: 'DeFi Sniper',
      nftId: '7',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/defiSniper.svg',
      description: 'Accuracy under pressure. Plasma bows to your aim.',
      criteria: '10 profitable trades (each ≥ $5,000 notional)',
      type: 'Activity',
      category: 'Trading Skill',
      minPoints: 1000,
      pointsValue: '750',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Liquidation Dodger',
      nftId: '8',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/liquidationDodger.svg',
      description: 'Master of risk, survivor of storms.',
      criteria: 'Maintain ≥ $1,000 open margin for 30 days with zero liquidations',
      type: 'Activity',
      category: 'Trading Skill',
      minPoints: 1000,
      pointsValue: '750',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Leverage Lord',
      nftId: '9',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/leverageLord.png',
      description: 'You bend volatility to your will.',
      criteria: 'Hold a ≥ 20x position for 10 consecutive days without liquidation',
      type: 'Activity',
      category: 'Trading Skill',
      minPoints: 1000,
      pointsValue: '750',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Ionex Initiate',
      nftId: '10',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexInitiate.svg',
      description: 'First sparks earned. The ecosystem’s starting to notice you.',
      criteria: 'Earn ≥ 1,000 Ionex Points',
      type: 'Activity',
      category: 'Mining',
      minPoints: 1000,
      pointsValue: '10',
      totalWalletCap: 10000,
      active: true,
    },
    {
      name: 'Ionex Operator',
      nftId: '11',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexOperator.svg',
      description: 'You’ve leveled up your grind, nice work.',
      criteria: 'Earn ≥ 50,000 Ionex Points',
      type: 'Activity',
      category: 'Mining',
      minPoints: 50000,
      pointsValue: '500',
      totalWalletCap: 5000,
      active: true,
    },
    {
      name: 'Ionex Specialist',
      nftId: '12',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexSpecialist.svg',
      description: 'Stacking with skill. You know where the points live.',
      criteria: 'Earn ≥ 250,000 Ionex Points',
      type: 'Activity',
      category: 'Mining',
      minPoints: 250000,
      pointsValue: '2500',
      totalWalletCap: 5000,
      active: true,
    },
    {
      name: 'Ionex Master',
      nftId: '13',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexMaster.png',
      description: 'You don’t chase points, they come to you now.',
      criteria: 'Earn ≥ 1,000,000 Ionex Points',
      type: 'Activity',
      category: 'Mining',
      minPoints: 1000000,
      pointsValue: '10000',
      totalWalletCap: 1000,
      active: true,
    },
    {
      name: 'Ionex Elite',
      nftId: '14',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexElite.svg',
      description: 'You’ve gamed the system flawlessly.',
      criteria: 'Earn ≥ 10,000,000 Ionex Points',
      type: 'Activity',
      category: 'Mining',
      minPoints: 10000000,
      pointsValue: '100000',
      totalWalletCap: 50,
      active: true,
    },
    {
      name: 'Ionex OG',
      nftId: '15',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ionexOg.png',
      description: 'You were here before the noise. The real ones remember.',
      criteria: 'Be among the first 100 traders on Ionex',
      type: 'Activity',
      category: 'Community',
      minPoints: 1000,
      pointsValue: '100',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Signal Bearer',
      nftId: '16',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/signalBearer.png',
      description: 'You spread the first ripple through the network.',
      criteria: 'Refer 1 verified trader',
      type: 'Activity',
      category: 'Community',
      minPoints: 1000,
      pointsValue: '100',
      totalWalletCap: 5000,
      active: false,
    },
    {
      name: 'Wave Starter',
      nftId: '17',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/waveStarter.svg',
      description: 'You’ve kicked off real momentum. Your circle’s catching on fast.',
      criteria: 'Refer 5 verified trader',
      type: 'Activity',
      category: 'Community',
      minPoints: 1000,
      pointsValue: '600',
      totalWalletCap: 2500,
      active: false,
    },
    {
      name: 'Flow Conductor',
      nftId: '18',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/flowConductor.svg',
      description: 'You’ve turned connections into current.',
      criteria: 'Refer 15 verified traders',
      type: 'Activity',
      category: 'Community',
      minPoints: 1000,
      pointsValue: '1800',
      totalWalletCap: 800,
      active: false,
    },
    {
      name: 'Network Architect',
      nftId: '19',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/networkArchitect.svg',
      description: 'You built the structure others trade on.',
      criteria: 'Refer 50 verified traders',
      type: 'Activity',
      category: 'Community',
      minPoints: 1000,
      pointsValue: '5500',
      totalWalletCap: 50,
      active: false,
    },
    {
      name: 'Lynex',
      nftId: '20',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/lynex.png',
      description: 'You don’t just vote, you govern. And your lock calls the shots.',
      criteria: 'veLYNX holders with a veNFT with a minimum one-year lock',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'Amounts are proportional to voting power.',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Ocelex',
      nftId: '21',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ocelex.png',
      description: 'You don’t just vote, you govern. And your lock calls the shots.',
      criteria: 'veOCX holders with a veNFT with a minimum one-year lock',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'Amounts are proportional to voting power.',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Catex',
      nftId: '22',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/catex.png',
      description: 'You don’t just vote, you govern. And your lock calls the shots.',
      criteria: 'veCATX holders with a veNFT with a minimum one-year lock',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'Amounts are proportional to voting power.',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Pumex',
      nftId: '23',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/pumex.png',
      description: '',
      criteria: 'LPs – minimum XXX points',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'NaN',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Hydrex',
      nftId: '24',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/hydrex.png',
      description: 'You don’t just vote, you govern. And your lock calls the shots.',
      criteria: 'TBD – Top holders',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'Amounts are proportional to voting power.',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Thena',
      nftId: '25',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/thena.png',
      description: 'You don’t just vote, you govern. And your lock calls the shots.',
      criteria: 'TBD – Top holders',
      type: 'Activity',
      category: 'veGovernators',
      minPoints: 1000,
      pointsValue: 'Amounts are proportional to voting power.',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Euler',
      nftId: '26',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/euler.svg',
      criteria: 'Users who are using their Multiplies looping product',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '500',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Aave',
      nftId: '27',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/aave.svg',
      criteria: 'supplying WXPL on aave v3',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '500',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Gearbox',
      nftId: '28',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/gearbox.svg',
      criteria: 'Supply USDT0 on Plasma to Invariant Group',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '500',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Beefy',
      nftId: '29',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/beefy.svg',
      criteria: 'Deposit USDT0-WXPL on Beefy',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '500',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'ApeBond',
      nftId: '30',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/apeBond.svg',
      criteria: 'Bond Kima',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '500',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Trevee',
      nftId: '31',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/trevee.svg',
      criteria: 'Stake plUSD',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '350',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Chateau Capital',
      nftId: '32',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/chateauCapital.svg',
      criteria: 'Hold schUSD',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '350',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Ebisu',
      nftId: '33',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/ebisu.svg',
      criteria: 'Supply sUSDai on Ebisu at Plasma chain.',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '350',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Metronome',
      nftId: '34',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/metronome.svg',
      criteria: 'Quests around app.odyssey.finance',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '200',
      totalWalletCap: 100,
      active: false,
    },
    {
      name: 'Petrillions',
      nftId: '35',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/petrillions.svg',
      criteria: 'Hold a Pretrillions NFT',
      type: 'Activity',
      category: 'Partners',
      minPoints: 1000,
      pointsValue: '200',
      totalWalletCap: 100,
      active: false,
    },
  ],
  "1776": [
    {
      name: 'Outpost',
      nftId: '1',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 1,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 1000,
      pointsValue: '250',
      totalWalletCap: 600,
      active: false,
    },
    {
      name: 'Watchtower',
      nftId: '2',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 25,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 25000,
      pointsValue: '1000',
      totalWalletCap: 400,
      active: false,
    },
    {
      name: 'Garrison',
      nftId: '3',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 100,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 100000,
      pointsValue: '3000',
      totalWalletCap: 240,
      active: false,
    },
    {
      name: 'Fortress',
      nftId: '4',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 300,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 300000,
      pointsValue: '7500',
      totalWalletCap: 120,
      active: false,
    },
    {
      name: 'Province',
      nftId: '5',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 1,000,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 1000000,
      pointsValue: '20000',
      totalWalletCap: 50,
      active: false,
    },
    {
      name: 'Shogunate',
      nftId: '6',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Earn at least 2,500,000 IP',
      type: 'Activity',
      category: 'Balance',
      minPoints: 2500000,
      pointsValue: '50000',
      totalWalletCap: 20,
      active: false,
    },
    {
      name: 'Initiate',
      nftId: '7',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $100 on Pumex.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '100',
      totalWalletCap: 300,
      active: false,
    },
    {
      name: 'Apprentice',
      nftId: '8',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $500 on Pumex.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '300',
      totalWalletCap: 200,
      active: false,
    },
    {
      name: 'Adept',
      nftId: '9',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $2,500 on Pumex.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '800',
      totalWalletCap: 120,
      active: false,
    },
    {
      name: 'Duelist',
      nftId: '10',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $10,000 on Pumex',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '2000',
      totalWalletCap: 60,
      active: false,
    },
    {
      name: 'Sensei',
      nftId: '11',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $100,000 on Pumex',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '5000',
      totalWalletCap: 25,
      active: false,
    },
    {
      name: 'Grandmaster',
      nftId: '12',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Trade more than $1,000,000 on Pumex',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '12500',
      totalWalletCap: 10,
      active: false,
    },
    {
      name: 'Dojo Pathfinder (Testnet)',
      nftId: '13',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Interacted with Pumex Testnet (swap or LP) before mainnet launch.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '250',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Ninja Scout (Testnet)',
      nftId: '14',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Minted the “Pumex Ninja” NFT on Rarible with the same wallet used on Injective.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '250',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Roar Champion',
      nftId: '15',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Be placed in a Roar2Earn leaderboard week during the campaign (per official winners list).',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '500',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Founding OG',
      nftId: '16',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Hold the @OG role in the ZooFelines Discord at the Initiation snapshot (role must be present at snapshot time).',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '250',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Injective Envoy',
      nftId: '17',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'You can claim this badge if you are a recognized KOL/creator participating in the Bantr × Injective activation campaign.',
      type: 'Activity',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '2500',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Clan Ally: INCELS',
      nftId: '18',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Hold an INCELS NFT in the same wallet on Injective at the time of claim (verified via partner list).',
      type: 'Partner',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '1000',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Clan Ally: Premier Ninjas',
      nftId: '19',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Hold a Premier Ninjas NFT in the same wallet on Injective at the time of claim (verified via partner list).',
      type: 'Partner',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '1000',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Clan Ally: QAUNTS',
      nftId: '20',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Hold a QUANTS NFT',
      type: 'Partner',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '1000',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
    {
      name: 'Clan Ally: Nonjas',
      nftId: '21',
      image: 'https://cdn.jsdelivr.net/gh/Lynexfi/lynex-lists@main/tokens/badge-logos/ionex-tasks/',
      description: 'Hold a Premier QAUNTS NFT in the same wallet on Injective at the time of claim (verified via partner list).',
      type: 'Partner',
      category: 'Balance',
      minPoints: 200,
      pointsValue: '1000',
      totalWalletCap: 99999999999999999999999999999999999999999999999999999999,
      active: false,
    },
  ],
};

