import { tokens, Strategist, StrategyType , ChainId} from '../types/index';

const strategies = [
  {
    symbol: 'BUSD/WETH Narrow',
    title: 'GAMMA_NARROW',
    chainId: ChainId.LINEA_MAINNET,
    type: StrategyType.Narrow,
    strategist: Strategist.Gamma,
    allowed0: true,
    allowed1: true,
    address: '0x6e9d701fb6478ed5972a37886c2ba6c82a4cbb4c',
    token0: tokens.busd,
    token1: tokens.weth,
  },
  {
    symbol: 'WBTC/WETH Narrow',
    title: 'GAMMA_NARROW',
    chainId: ChainId.LINEA_MAINNET,
    type: StrategyType.Narrow,
    strategist: Strategist.Gamma,
    allowed0: true,
    allowed1: true,
    address: '0x8a9570ec97534277ade6e46d100939fbce4968f0',
    token0: tokens.wbtc,
    token1: tokens.weth,
  },
  {
    symbol: 'USDC/BUSD Stable',
    title: 'GAMMA_STABLE',
    chainId: ChainId.LINEA_MAINNET,
    type: StrategyType.Stable,
    strategist: Strategist.Gamma,
    allowed0: true,
    allowed1: true,
    address: '0xd6cc4a33da7557a629e819c68fb805ddb225f517',
    token0: tokens.usdc,
    token1: tokens.busd,
  },
  {
    symbol: 'BUSD/USDT Stable',
    title: 'GAMMA_STABLE',
    chainId: ChainId.LINEA_MAINNET,
    type: StrategyType.Stable,
    strategist: Strategist.Gamma,
    allowed0: true,
    allowed1: true,
    address: '0x32e27ff479454e32868ff67ee9f06bafdc1e908f',
    token0: tokens.busd,
    token1: tokens.usdt,
  },
  {
    symbol: 'USDT/WETH Narrow',
    title: 'GAMMA_NARROW',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0xf3b1125c8505f038503e002e61a78253610d4f60',
    token0: tokens.usdt,
    token1: tokens.weth,
  },
  {
    symbol: 'USDC/WETH Narrow',
    title: 'GAMMA_NARROW',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0x0b15a5e3ca0d4b492c3b476d0f807535f9b72079',
    token0: tokens.usdc,
    token1: tokens.weth,
  },
  {
    symbol: 'MATIC/WETH Narrow',
    title: 'GAMMA_NARROW',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0x8421c6102ee8a147facc01977df3b159f7921d54',
    token0: tokens.matic,
    token1: tokens.weth,
  },
  {
    symbol: 'USDC/LYNX Wide',
    title: 'Gamma Wide',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Wide',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0xcC86572Ce5a6EEe74c76c57E9ea7b08221F06bb9',
    token0: tokens.usdc,
    token1: tokens.lynx,
  },
  {
    symbol: 'wBTC/USDC Narrow',
    title: 'Gamma Narrow',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0xa3d9745dcd138bd2ba4b039fa61c042756bfe1e8',
    token0: tokens.usdc,
    token1: tokens.wbtc,
  },
  {
    symbol: 'wstETH/ETH Correlated',
    title: 'Gamma Correlated',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0xEa5abd5d15B8CD168e9eFf78047DB52aF079e094',
    token0: tokens.wsteth,
    token1: tokens.weth,
  },
  {
    symbol: 'STONE/ETH Correlated',
    title: 'Gamma Correlated',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0xcfFBFD665BEdB19B47837461A5aBf4388C560D35',
    token0: tokens.stone,
    token1: tokens.weth,
  },
  {
    symbol: 'ezETH/ETH Correlated',
    title: 'Gamma Correlated',
    chainId: ChainId.LINEA_MAINNET,
    type: 'Narrow',
    strategist: 'Gamma',
    allowed0: true,
    allowed1: true,
    address: '0x392AC7d2D09042EC9fAfAEb8D52a88Dc591E9feA',
    token0: tokens.ezeth,
    token1: tokens.weth,
  },

  /************ ICHI Strategies Starts Here ************/
  {
    symbol: 'USDC/WETH Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    strategist: 'Ichi',
    address: '0x4f74ED3b2278dAE2119658aB2c235BBcd2306d29',
    depositToken: tokens.usdc,
    allowed0: true,
    allowed1: false,
    token0: tokens.usdc,
    token1: tokens.weth,
  },
  {
    symbol: 'WETH/USDC Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    strategist: 'Ichi',
    address: '0x00b34e51ac2a78761982485a618b235a211f5d86',
    depositToken: tokens.weth,
    allowed0: false,
    allowed1: true,
    token0: tokens.weth,
    token1: tokens.usdc,
  },
  {
    symbol: 'wBTC/WETH Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    strategist: 'Ichi',
    address: '0xad53f20917b144cd0b100dbe75988c0e4b919dba',
    depositToken: tokens.wbtc,
    allowed0: true,
    allowed1: false,
    token0: tokens.wbtc,
    token1: tokens.weth,
  },
  {
    symbol: 'wETH/LYNX',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    strategist: 'Ichi',
    address: '0x511481ef0DEB10eB5c1E36B72140718c58921265',
    depositToken: tokens.weth,
    allowed0: false,
    allowed1: true,
    token0: tokens.weth,
    token1: tokens.lynx,
  },
  {
    symbol: 'USDC/LYNX Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    strategist: 'Ichi',
    address: '0x92ccb773da4f3974c941974bDb978bAd7efa7744',
    depositToken: tokens.usdc,
    allowed0: true,
    allowed1: false,
    token0: tokens.usdc,
    token1: tokens.lynx,
  },
  {
    symbol: 'wBTC/LYNX Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ (wBTC)',
    chainId: ChainId.LINEA_MAINNET,
    type: 'yieldiq',
    address: '0xae5e4a028120b711c5c5dc8a9162bcdaa88936ae',
    depositToken: tokens.wbtc,
    strategist: 'Ichi',
    allowed0: false,
    allowed1: true,
    token0: tokens.lynx,
    token1: tokens.wbtc,
  },
  {
    symbol: 'USDT/LYNX Narrow',
    title: 'Yield IQ (USDT)',
    type: 'YieldIQ',
    strategist: 'Ichi',
    allowed0: false,
    allowed1: true,
    address: '0x555267747b0918ABce10335F154FbE7B636F7804',
    depositToken: tokens.usdt,
    token0: tokens.lynx,
    token1: tokens.usdt,
    chainId: ChainId.LINEA_MAINNET
  },
  {
    symbol: 'STONE/LYNX Narrow',
    title: 'Yield IQ (STONE)',
    type: 'YieldIQ',
    chainId: ChainId.LINEA_MAINNET,
    strategist: 'Ichi',
    allowed0: false,
    allowed1: true,
    address: '0xe57F293520CBf7d5a17629CbFB06eAbdb759a151',
    depositToken: tokens.stone,
    token0: tokens.lynx,
    token1: tokens.stone,
  },
  {
    symbol: 'wETH/LYNX',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    type: 'yieldiq',
    chainId: ChainId.LINEA_MAINNET,
    strategist: 'Ichi',
    address: '0x511481ef0DEB10eB5c1E36B72140718c58921265',
    depositToken: tokens.weth,
    allowed0: false,
    allowed1: true,
    token0: tokens.weth,
    token1: tokens.lynx,
  },
  {
    symbol: 'USDC/LYNX Narrow',
    rewardAddress: tokens.lynx,
    title: 'Yield IQ',
    type: 'yieldiq',
    chainId: ChainId.LINEA_MAINNET,
    address: '0x92ccb773da4f3974c941974bDb978bAd7efa7744',
    depositToken: tokens.usdc,
    strategist: 'Ichi',
    allowed0: true,
    allowed1: false,
    token0: tokens.usdc,
    token1: tokens.lynx,
  },
  {
    symbol: 'wBTC/LYNX Narrow',
    title: 'Yield IQ (wBTC)',
    type: 'yieldiq',
    chainId: ChainId.LINEA_MAINNET,
    rewardAddress:tokens.lynx,
    strategist: 'Ichi',
    address: '0xae5e4a028120b711c5c5dc8a9162bcdaa88936ae',
    depositToken: tokens.wbtc,
    allowed0: false,
    allowed1: true,
    token0: tokens.lynx,
    token1: tokens.wbtc,
  },
  {
    symbol: 'USDT/LYNX Narrow',
    title: 'Yield IQ (USDT)',
    type: 'YieldIQ',
    strategist: 'Ichi',
    allowed0: false,
    allowed1: true,
    address: '0x555267747b0918ABce10335F154FbE7B636F7804',
    depositToken: tokens.usdt,
    token0: tokens.lynx,
    token1: tokens.usdt,
    chainId: ChainId.LINEA_MAINNET
  },
  {
    symbol: 'STONE/LYNX Narrow',
    title: 'Yield IQ (STONE)',
    type: 'YieldIQ',
    strategist: 'Ichi',
    allowed0: false,
    allowed1: true,
    address: '0xe57F293520CBf7d5a17629CbFB06eAbdb759a151',
    depositToken: tokens.stone,
    token0: tokens.lynx,
    token1: tokens.stone,
    chainId: ChainId.LINEA_MAINNET
  },
   /************ Steer Vaults Starts Here ************/
   {
    symbol: 'USDC/USDT Narrow',
    title: 'Steer Stable',
    type: 'Stable',
    strategist: 'Steer',
    allowed0: true,
    allowed1: true,
    address: '0x2babed912322c355f4b8b58ea568727892ca3f05',
    depositToken: tokens.usdc,
    token0: tokens.usdc,
    token1: tokens.usdt,
    chainId: ChainId.LINEA_MAINNET
  },
  {
    symbol: 'USDC/EUR3 Narrow',
    title: 'Steer Stable',
    type: 'Stable',
    strategist: 'Steer',
    allowed0: true,
    allowed1: true,
    address: '0x77a0006fdeb1ce7f521a01852a632b2a21490d67',
    depositToken: tokens.usdc,
    token0: tokens.usdc,
    token1: tokens.euro3,
    chainId: ChainId.LINEA_MAINNET
  },

  /************  Testnet Strategies Starts Here ************/
  {
    symbol: 'USDC/WETH Narrow',
    title: 'GAMMA_NARROW',
    type: 'Narrow',
    strategist: 'Gamma',
    address: '0x6e9d701fB6478Ed5972a37886C2BA6C82a4cBb4C',
    depositToken: tokens.weth,
    token0: tokens.usdc,
    token1: tokens.weth,
    allowed0: true,
    allowed1: true,
    chainId: ChainId.LINEA_TESTNET
  },
];

export { strategies };
